global:
  scrape_interval: 1m    
  scrape_timeout: 15s 
  evaluation_interval: 2m 

  external_labels:
    monitor: 'account-monitor'      
  query_log_file: query_log_file.log 

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'monitoring-item' 
    metrics_path: '/actuator/prometheus'   
    honor_labels: false       
    honor_timestamps: false   
    scheme: 'http'            

    static_configs:
      - targets: ["host.docker.internal:1011"]
        labels:
          service: "batch"
          application: "Batch Server"
          namespace: "Local"
      - targets: ["host.docker.internal:1010"]
        labels:
          service: "api"
          application: "API Server"
          namespace: "Local"
          
      - targets: ["172.31.38.96:1011"]  # Private IP of the EC2 instance
        labels:
          service: "batch"
          application: "Batch Server"
          namespace: "Dev"
      - targets: ["172.31.38.96:1010"]  # Private IP of the EC2 instance
        labels:
          service: "api"
          application: "API Server"
          namespace: "Dev"
