spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${dev-db.host}:${dev-db.port}/${dev-db.name}
    username: ${dev-db.username}
    password: ${dev-db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: validate
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true

batch:
  url: https://batch.joon6093.link

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.transaction.interceptor: trace
