spring:
  datasource:
    meta:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${local.meta-db.host}:${local.meta-db.port}/${local.meta-db.name}
        username: ${local.meta-db.username}
        password: ${local.meta-db.password}
        auto-commit: false

    domain:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${local.domain-db.host}:${local.domain-db.port}/${local.domain-db.name}
        username: ${local.domain-db.username}
        password: ${local.domain-db.password}
        auto-commit: false

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: validate
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.transaction.interceptor: trace
