server:
  port: 8081

spring:
  profiles:
    default: local

  config:
    import:
      - security/application-db.yml
      - security/application-oauth2.yml
      - security/application-paymentgateway.yml

  quartz:
    scheduler-name: QuartzScheduler
    jdbc:
      initialize-schema: never
    job-store-type: jdbc

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
