server:
  port: 8081

spring:
  profiles:
    default: local

  config:
    import:
      - security/application-db.yml
      - security/application-oauth2.yml
      - security/application-paymentgateway.yml

  quartz:
    scheduler-name: QuartzScheduler
    jdbc:
      initialize-schema: never
    job-store-type: jdbc

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
