spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: monitoring
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
  application:
    name: monitoring
server:
  port: 8010